server:
  port: 8081

spring:
  application:
    name: auth-service
  # PgSQL auth-db
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Grpc Client
  grpc:
    server:
      enabled: false
    client:
      local-grpc-server:
        address: 'static://127.0.0.1:9000'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext
      channels:
        user:
          address: 'static://localhost:9090'

jwt:
  secret: "mi-super-clave-ultra-segura-de-64-caracteres-2025-1234567890"
  expiration: 3600000 # 1 hora (opcional)
  jwks-path: /.well-known/jwks.json
  access-token-ttl: 900 # seconds
  refresh-token-ttl: 2592000 # 30 days