FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

# copiamos pom para cachear dependencias
COPY pom.xml .

RUN mvn dependency:go-offline -B

# copiamos el código después
COPY src ./src

# exposición
EXPOSE 4000

CMD ["mvn","spring-boot:run"]
