services:
  backend:
    build: .
    image: socialseed-backend:0.0.1
    container_name: backend-service
    ports:
      - "8081:8081"
    depends_on:
      neo4j-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_NEO4J_URI=bolt://neo4j-db:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=neo4jSocial

  neo4j-db:
    image: neo4j:5.26.12-community
    container_name: neo4j-db
    ports:
      - "7474:7474"   # consola web
      - "7687:7687"   # bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jSocial
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p neo4jSocial 'RETURN 1' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5