version: '3.9'
services:
  backend:
    build: .
    image: socialseed-backend:0.0.1
    container_name: backend-service
    ports:
      - "8081:8081"
    depends_on:
      neo4j-db:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
#      keycloak:
#        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_NEO4J_URI=bolt://neo4j-db:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=neo4jSocial
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/socialseed-auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=neo4jSocial
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/socialseed-realm

  neo4j-db:
    image: neo4j:5.26.12-community
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jSocial
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p neo4jSocial 'RETURN 1'" ]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: socialseed-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: neo4jSocial
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d socialseed-auth"]
      interval: 10s
      timeout: 5s
      retries: 5

#  keycloak-db:
#    image: postgres:16
#    container_name: keycloak-db
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: keycloakpass
#    volumes:
#      - ./keycloak/postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:26.3
#    container_name: keycloak
#    command:
#      - start-dev
#      - --import-realm
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_DB=postgres
#      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=keycloakpass
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./keycloak/realms:/opt/keycloak/data/import
#    depends_on:
#      keycloak-db:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
#      interval: 15s
#      timeout: 10s
#      retries: 10
