services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4005/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 20

  # Auth database for auth-service
  auth-db:
    container_name: auth-db
    image: postgres:17
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - /home/dairon/db_volumes/postgres_data/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authuser -d authdb" ]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  net: