version: "3.9"
services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "8081:8081"
    depends_on:
      - neo4j
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jSocial

  neo4j:
    image: neo4j:5.26.12-community
    container_name: neo4j-db
    ports:
      - "7474:7474"   # consola web
      - "7687:7687"   # bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jSocial
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins