server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neoSocial
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: socialuser-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    listener:
      auto-startup: true

grpc:
  server:
    port: 9090
    reflection-service-enabled: true
    security:
      enabled: false
