server:
  port: 8090
  #port: 4005

logging:
  level:
    root: info
    org.springframework.context.support: DEBUG


# ======================
# Neo4j Configuration (Aura Cloud)
# ======================
spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: socialuser-service
  neo4j:
    # Cambiamos bolt://localhost por la URI de Aura
    # Es vital usar neo4j+s:// para conexiones seguras con Aura
    uri: neo4j+s://89861427.databases.neo4j.io
        # uri: bolt://localhost:7687
#    uri: bolt://socialgraph-db:7687
    authentication:
      username: neo4j
      password: 4J49pcAZnhOZOkzlPbkg3JmySg3jQus7OP-phX5vFPk
      # username: neo4j
      # password: neoSocial

management:
  endpoints:
    web:
      exposure:
        include: health

# ======================
# Grpc
# ======================
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
    security:
      enabled: false

