server:
  port: 8081

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: socialuser-service-route
              uri: http://socialuser-dev:4000
              predicates:
              - Path=/api/users/**
              filters:
              - StripPrefix=0
              # REST CLIENT -> http://localhost:8081/api/users
              # API GATEWAY -> http://socialuser-dev:4000