server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD:-}
  grpc:
    client:
      channels:
        user:
          address: localhost:9090
        socialuser-service:
          address: localhost:9090
  kafka:
    bootstrap-servers: localhost:9092
