server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
