server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6380
  grpc:
    client:
      user:
        address: 'static://localhost:9090'
        negotiationType: plaintext
      socialuser-service:
        address: 'static://localhost:9090'
        negotiationType: plaintext
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
