server:
  port: 8081

spring:
  application:
    name: auth-service
  # PgSQL auth-db
  datasource:
    # Docker
    url: jdbc:postgresql://auth-db:5432/authdb
    # Local
#    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Grpc Client
  grpc:
    server:
      enabled: false
    client:
      user:
        address: 'static://localhost:9090'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext
      channels:
        user:
          address: 'static://localhost:9090'
  # Kafka emiter
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    properties:
      spring.json.add.type.headers: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

kafka:
  topic:
    auth-user-registered: auth.user.registered

jwt:
  secret: "mi-super-clave-ultra-segura-de-64-caracteres-2025-1234567890"
  expiration: 3600000 
  jwks-path: /.well-known/jwks.json
  access-token-ttl: 900 # seconds
  refresh:
    expiration: 2592000 # 30 days