server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  grpc:
    client:
      channels:
        user:
          address: ${SPRING_GRPC_CLIENT_CHANNELS_USER_ADDRESS:static://socialuser-service:9090}
        socialuser-service:
          address: ${SPRING_GRPC_CLIENT_CHANNELS_SOCIALUSER_ADDRESS:static://socialuser-service:9090}
  kafka:
    bootstrap-servers: kafka:9092
