spring.application.name=socialuser-service

server.port=8090
#server.port=4000
logging.level.root=info

# ======================
# Neo4j
# ======================
#spring.neo4j.uri=bolt://socialgraph-db:7687
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neoSocial

# ======================
# Language
# ======================
#spring.messages.basename=i18n/messages
#spring.messages.encoding=UTF-8

management.endpoints.web.exposure.include=health
