// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: socialuser.proto
// Protobuf Java Version: 4.32.1

package com.socialseed.socialuserservice.proto;

@com.google.protobuf.Generated
public interface CreateUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * UUID generado
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * UUID generado
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Mensaje de confirmación
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Mensaje de confirmación
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
