// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: socialuser.proto
// Protobuf Java Version: 4.32.1

package com.socialseed.socialuserservice.proto;

@com.google.protobuf.Generated
public final class SocialUserProto extends com.google.protobuf.GeneratedFile {
  private SocialUserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      SocialUserProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateUserReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020socialuser.proto\"4\n\021CreateUserRequest\022" +
      "\020\n\010username\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"2\n\017Crea" +
      "teUserReply\022\016\n\006userId\030\001 \001(\t\022\017\n\007message\030\002" +
      " \001(\t2G\n\021SocialUserService\0222\n\nCreateUser\022" +
      "\022.CreateUserRequest\032\020.CreateUserReplyB;\n" +
      "&com.socialseed.socialuserservice.protoB" +
      "\017SocialUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateUserRequest_descriptor,
        new java.lang.String[] { "Username", "Email", });
    internal_static_CreateUserReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateUserReply_descriptor,
        new java.lang.String[] { "UserId", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
