### Change Password of SocialUser
POST http://localhost:8090/socialusers/me/password/change
Content-Type: application/json
Accept-Language: en

{
  "id": "db15c0c0-6096-4794-82a4-c7a7326b6908",
  "currentPassword": "contratona",
  "newPassword": "lucas2@gmail.com"
}
###