### Create a new socialuser entity
#POST http://localhost:8085/api/socialusers
POST http://localhost:8090/socialusers
Content-Type: application/json
Accept-Language: en

{
  "email": "jondoe@gmail.com",
  "password":"jonpassword",
  "username": "jonodoe",
  "fullName": "Jhon Does"
}
###