### Update SocialUser entity
PUT http://localhost:8090/api/socialusers/b62a4b76-a946-43f6-a392-3c289d869a4a
Content-Type: application/json

{
  "username": "Lucas Das",
  "email": "lucas2@gmail.com",
  "fullName": "18 main street"
}
###