syntax = "proto3";

option java_package = "com.socialseed.socialuserservice.proto";
option java_multiple_files = true;
option java_outer_classname= "SocialUserProto";

// Servicio gRPC que expone SocialUserService
service SocialUserService {
  // Crea un usuario con username y email
  rpc CreateUser(CreateUserRequest) returns (CreateUserReply);
}

// Mensaje que recibe auth-service
message CreateUserRequest {
  string username = 1;
  string email = 2;
}

// Mensaje que devuelve socialuser-service
message CreateUserReply {
  string userId = 1;       // UUID generado
  string message = 2;      // Mensaje de confirmación
}
