CREATE CONSTRAINT usersId IF NOT EXISTS FOR (u:SocialUser) REQUIRE u.id IS UNIQUE;
CREATE CONSTRAINT usersEmail IF NOT EXISTS FOR (u:SocialUser) REQUIRE u.email IS UNIQUE;
CREATE CONSTRAINT userName IF NOT EXISTS FOR (u:SocialUser) REQUIRE u.userName IS UNIQUE;
CREATE CONSTRAINT postId IF NOT EXISTS FOR (p:Post) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT hashTagId IF NOT EXISTS FOR (t:HashTag) REQUIRE t.id IS UNIQUE;
