### Change Password
POST http://localhost:8081/auth/changepassword
Content-Type: application/json
Accept-Language: en

{
  "currentPassword": "ssxxx",
  "newPassword": "ss",
  "id": "bf6d2550-5e88-495d-bfd4-07e81cc28bda"
}
###