server:
  port: 8086

spring:
  application:
    name: nexus-service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info
