// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AuthUserRegistered.proto
// Protobuf Java Version: 4.32.1

package com.socialseed.auth;

@com.google.protobuf.Generated
public final class AuthUserRegisteredOuterClass extends com.google.protobuf.GeneratedFile {
  private AuthUserRegisteredOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      AuthUserRegisteredOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socialseed_auth_AuthUserRegistered_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socialseed_auth_AuthUserRegistered_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030AuthUserRegistered.proto\022\023com.socialse" +
      "ed.auth\"X\n\022AuthUserRegistered\022\016\n\006userId\030" +
      "\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\020\n\010username\030\003 \001(\t\022\021" +
      "\n\tcreatedAt\030\004 \001(\003B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_socialseed_auth_AuthUserRegistered_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_socialseed_auth_AuthUserRegistered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_socialseed_auth_AuthUserRegistered_descriptor,
        new java.lang.String[] { "UserId", "Email", "Username", "CreatedAt", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
