// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AuthUserRegistered.proto
// Protobuf Java Version: 4.32.1

package com.socialseed.auth;

@com.google.protobuf.Generated
public interface AuthUserRegisteredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.socialseed.auth.AuthUserRegistered)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * Timestamp en epoch millis
   * </pre>
   *
   * <code>int64 createdAt = 4;</code>
   * @return The createdAt.
   */
  long getCreatedAt();
}
